logging:
    file:
        name: pupperfield.log
    logback:
        rollingpolicy:
            max-history: 31

server:
    compression:
        enabled: true
        min-response-size: 1024
    error:
        include-exception: false
        include-message: never
        include-path: never
        include-stacktrace: never
        whitelabel:
            enabled: false
    http2:
        enabled: true
    port: 8080

spring:
    application:
        name: pupperfield
    cache:
        cache-names:
            - breeds
            - lists
            - searches
    jpa:
        open-in-view: false
    main:
        banner-mode: off
    threads:
        virtual:
            enabled: true

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        display-request-duration: true
