logbook:
    obfuscate:
        headers: []

logging:
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
            springframework:
                cache: trace
        sql: trace
        web: trace

server:
    error:
        include-exception: true
        include-message: always
        include-path: always
        include-stacktrace: always

spring:
    jpa:
        show-sql: true
