logging:
    file:
        name: pupperfield.log
    logback:
        rollingpolicy:
            max-history: 31

server:
    compression:
        enabled: true
        min-response-size: 1024
    error:
        include-exception: false
        include-message: never
        include-path: never
        include-stacktrace: never
        whitelabel:
            enabled: false
    http2:
        enabled: true
    port: 8080

spring:
    application:
        name: pupperfield
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:src/main/resources/database/dogs.db
    jpa:
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        hibernate:
            ddl-auto: validate
    main:
        banner-mode: off
    threads:
        virtual:
            enabled: true
